version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"

  flask-app:
    build:
      context: .
    container_name: flask-app
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    environment:
      - FLASK_APP=app.main
      - FLASK_ENV=development
    depends_on:
      - redis

  celery-worker:
    build:
      context: .
    container_name: celery-worker
    command: celery -A app.tasks worker --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
